---
- name: Install yum dependency
  yum:
    name: "{{ item }}"
  loop:
    - python3
    - python3-pip
    - python3-devel
    - centos-release-openstack-train
    - rsync
    - rsyslog
    - memcached

- name: Install yum dependency
  yum:
    name: "{{ item }}"
  loop:
    - liberasurecode
    - liberasurecode-devel

- name: Update pip3
  shell: pip3 install -U pip

- name: Install swift python package
  pip:
    name:
      - swift==2.29.0
      - python-openstackclient==5.8.0
      - python-swiftclient==3.13.1
      - python3-memcached==1.51
      - keystonemiddleware==9.4.0
    executable: pip3
    extra_args: -i https://pypi.tuna.tsinghua.edu.cn/simple

- name: Create group "swift"
  group:
    name: swift
    state: present

- name: Add the user "swift"
  user:
    name: swift
    group: swift

- name: Create keystone configuration directory
  file:
    path: /etc/keystone
    state: directory
    mode: "0755"

- name: Create swift directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: swift
    group: swift
  loop:
    - /etc/swift
    - /var/cache/swift
    - /var/log/swift
    - /srv/node
